/**
 * Base de datos de herramientas
 * Creado por TheMarceloYT (https://github.com/TheMarceloYT)
 */

export class Herramientas {
	static herramientasContent = {
		c: {
			dataLang: "langC",
			dataTooltip: "c",
			sourceIMG: "/assets/images/herramientas/c_logo.webp",
			altIMG: "C logo",
			tooltipTarget: "c",
		},
		cpp: {
			dataLang: "langCPP",
			dataTooltip: "cpp",
			sourceIMG: "/assets/images/herramientas/cpp_logo.webp",
			altIMG: "C++ logo",
			tooltipTarget: "cpp",
		},
		csharp: {
			dataLang: "langCSHARP",
			dataTooltip: "csharp",
			sourceIMG: "/assets/images/herramientas/csharp_logo.webp",
			altIMG: "C# logo",
			tooltipTarget: "csharp",
		},
		html: {
			dataLang: "langHTML",
			dataTooltip: "html",
			sourceIMG: "/assets/images/herramientas/html_logo.webp",
			altIMG: "HTML logo",
			tooltipTarget: "html",
		},
		css: {
			dataLang: "langCSS",
			dataTooltip: "css",
			sourceIMG: "/assets/images/herramientas/css_logo.webp",
			altIMG: "CSS logo",
			tooltipTarget: "css",
		},
		laravel: {
			dataLang: "langLARAVEL",
			dataTooltip: "laravel",
			sourceIMG: "/assets/images/herramientas/laravel_logo.webp",
			altIMG: "LARAVEL logo",
			tooltipTarget: "laravel",
		},
		php: {
			dataLang: "langPHP",
			dataTooltip: "php",
			sourceIMG: "/assets/images/herramientas/php_logo.webp",
			altIMG: "PHP logo",
			tooltipTarget: "php",
		},
		typescript: {
			dataLang: "langTYPESCRIPT",
			dataTooltip: "typescript",
			sourceIMG: "/assets/images/herramientas/typescript_logo.webp",
			altIMG: "TYPESCRIPT logo",
			tooltipTarget: "typescript",
		},
		python: {
			dataLang: "langPYTHON",
			dataTooltip: "python",
			sourceIMG: "/assets/images/herramientas/python_logo.webp",
			altIMG: "PYTHON logo",
			tooltipTarget: "python",
		},
		puntoNET: {
			dataLang: "langPUNTONET",
			dataTooltip: "puntoNET",
			sourceIMG: "/assets/images/herramientas/puntoNET_logo.webp",
			altIMG: ".NET logo",
			tooltipTarget: "puntoNET",
		},
		dart: {
			dataLang: "langDART",
			dataTooltip: "dart",
			sourceIMG: "/assets/images/herramientas/dart_logo.webp",
			altIMG: "DART logo",
			tooltipTarget: "dart",
		},
		js: {
			dataLang: "langJS",
			dataTooltip: "langJS",
			sourceIMG: "/assets/images/herramientas/js_logo.webp",
			altIMG: "JS logo",
			tooltipTarget: "langJS",
		},
		flutter: {
			dataLang: "langFLUTTER",
			dataTooltip: "flutter",
			sourceIMG: "/assets/images/herramientas/flutter_logo.webp",
			altIMG: "FLUTTER logo",
			tooltipTarget: "flutter",
		},
		java: {
			dataLang: "langJAVA",
			dataTooltip: "java",
			sourceIMG: "/assets/images/herramientas/java_logo.webp",
			altIMG: "JAVA logo",
			tooltipTarget: "java",
		},
		oracleSQL: {
			dataLang: "langORACLESQL",
			dataTooltip: "oracleSQL",
			sourceIMG: "/assets/images/herramientas/oracleSQL_logo.webp",
			altIMG: "ORACLE SQL logo",
			tooltipTarget: "oracleSQL",
		},
		sqlSERVER: {
			dataLang: "langSQLSERVER",
			dataTooltip: "sqlSERVER",
			sourceIMG: "/assets/images/herramientas/SQLserver_logo.webp",
			altIMG: "SQL SERVER logo",
			tooltipTarget: "sqlSERVER",
		},
		react: {
			dataLang: "langREACT",
			dataTooltip: "react",
			sourceIMG: "/assets/images/herramientas/react_logo.webp",
			altIMG: "REACT logo",
			tooltipTarget: "react",
		},
		mariaDB: {
			dataLang: "langMARIADB",
			dataTooltip: "mariaDB",
			sourceIMG: "/assets/images/herramientas/mariadb_logo.webp",
			altIMG: "MARIADB logo",
			tooltipTarget: "mariaDB",
		},
		linux: {
			dataLang: "langLINUX",
			dataTooltip: "linux",
			sourceIMG: "/assets/images/herramientas/linux_logo.webp",
			altIMG: "LINUX logo",
			tooltipTarget: "linux",
		},
		nodeJS: {
			dataLang: "langNODEJS",
			dataTooltip: "nodeJS",
			sourceIMG: "/assets/images/herramientas/nodeJS_logo.webp",
			altIMG: "NODE JS logo",
			tooltipTarget: "nodeJS",
		},
		postman: {
			dataLang: "langPOSTMAN",
			dataTooltip: "postman",
			sourceIMG: "/assets/images/herramientas/postman_logo.webp",
			altIMG: "POSTMAN logo",
			tooltipTarget: "postman",
		},
		reING: {
			dataLang: "langREVERSEING",
			dataTooltip: "reverseING",
			sourceIMG: "/assets/images/herramientas/reverseING_logo.webp",
			altIMG: "INGENIERÍA INVERSA logo",
			tooltipTarget: "reverseING",
		},
		mySQL: {
			dataLang: "langMYSQL",
			dataTooltip: "mysql",
			sourceIMG: "/assets/images/herramientas/mysql_logo.webp",
			altIMG: "MYSQL logo",
			tooltipTarget: "mysql",
		},
		git: {
			dataLang: "langGIT",
			dataTooltip: "git",
			sourceIMG: "/assets/images/herramientas/git_logo.webp",
			altIMG: "GIT logo",
			tooltipTarget: "git",
		},
		django: {
			dataLang: "langDJANGO",
			dataTooltip: "django",
			sourceIMG: "/assets/images/herramientas/django_logo.webp",
			altIMG: "DJANGO logo",
			tooltipTarget: "django",
		},
		firebase: {
			dataLang: "langFIREBASE",
			dataTooltip: "firebase",
			sourceIMG: "/assets/images/herramientas/firebase_logo.webp",
			altIMG: "FIREBASE logo",
			tooltipTarget: "firebase",
		},
		codeigniter: {
			dataLang: "langCODEIGNITER",
			dataTooltip: "codeIgniter",
			sourceIMG: "/assets/images/herramientas/codeigniter_logo.webp",
			altIMG: "CODEIGNITER logo",
			tooltipTarget: "codeIgniter",
		},
		discord: {
			dataLang: "langDISCORD",
			dataTooltip: "discord",
			sourceIMG: "/assets/images/herramientas/discord_logo.webp",
			altIMG: "DISCORD logo",
			tooltipTarget: "discord",
		},
		aws: {
			dataLang: "langAWS",
			dataTooltip: "aws",
			sourceIMG: "/assets/images/herramientas/aws_logo.webp",
			altIMG: "AWS logo",
			tooltipTarget: "aws",
		},
		ia: {
			dataLang: "langIA",
			dataTooltip: "ia",
			sourceIMG: "/assets/images/herramientas/AI_logo.webp",
			altIMG: "IA logo",
			tooltipTarget: "ia",
		},
		bootstrap: {
			dataLang: "langBOOTSTRAP",
			dataTooltip: "bootstrap",
			sourceIMG: "/assets/images/herramientas/bootstrap_logo.webp",
			altIMG: "BOOTSTRAP logo",
			tooltipTarget: "bootstrap",
		},
		ghidra: {
			dataLang: "langGHIDRA",
			dataTooltip: "ghidra",
			sourceIMG: "/assets/images/herramientas/ghidra_logo.webp",
			altIMG: "GHIDRA logo",
			tooltipTarget: "ghidra",
		},
	};
}
